
spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: "PromoIt"
server:
  port: 8088