spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaCourse2024
    username: postgres
    password: postgre
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true